import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Jarvis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid grid-rows-1 h-screen bg-deep_space">
        <div className="flex flex-col gap-12 items-center justify-center">
          <div className="relative w-1/2 lg:w-1/3">
            <div className="absolute inset-0 bg-sky-400 rounded-full blur-2xl animate-pulse"></div>
            <img
              src="/jarvis.png"
              alt="virtual assistant"
              className="relative"
            ></img>
          </div>
          <button className="font-exo font-bold inline-flex items-center text-slate-800 text-2xl md:text-3xl lg:text-4xl bg-teal px-4 py-2 rounded-lg transition delay-100 duration-150 ease-in-out hover:scale-110 hover:bg-cyan-400">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth="1.5"
              stroke="currentColor"
              className="w-6 h-6 lg:w-8 lg:h-8 inline-block mr-1"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M12 18.75a6 6 0 006-6v-1.5m-6 7.5a6 6 0 01-6-6v-1.5m6 7.5v3.75m-3.75 0h7.5M12 15.75a3 3 0 01-3-3V4.5a3 3 0 116 0v8.25a3 3 0 01-3 3z"
              />
            </svg>
            Ask Jarvis
          </button>
        </div>
      </div>
    </>
  );
}
